[workspace]
[package]
name = "dsots"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
videoland = { path = "videoland" }

[workspace.dependencies]
egui = "0.24.1"
ahash = "0.8.6"

[workspace.lints.clippy]
single_match = "allow"
new_without_default = "allow"
