[package]
name = "videoland_ap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = { workspace = true }
hassle-rs = "0.10.0"
thiserror = { workspace = true }

[lints]
workspace = true
