[package]
name = "videoland"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ra = { path = "../ra" }
ra_egui = { path = "../ra_egui" }

ahash = "0.8.3"
bitflags = "2.4.1"
bytemuck = { version = "1.14.0", features = ["derive"] }
crossbeam-channel = "0.5.8"
dashmap = "5.5.3"
derive_more = "0.99.17"
dirs = "5.0.1"
egui = "0.24.1"
egui-winit = "0.24.1"
egui_tiles = "0.4.0"
glam = { version = "0.24.2", features = ["bytemuck"] }
hassle-rs = "0.10.0"
hecs = { version = "0.10.4" }
hecs-macros = "0.10.0"
indexmap = "2.0.2"
mlua = { version = "0.9.1", features = ["luau"] }
obj = "0.10.2"
physx-sys = "0.11.5"
raw-window-handle = "0.5.0"
rayon = "1.8.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.49"
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
uuid = { version = "1.4.1", features = ["v4"] }
walkdir = "2.4.0"
winit = { version = "0.29.3", features = ["rwh_05"] }

[features]
default = ["vk"]
vk = []
